### ISSUE TITLE
Improve handling of `UserRatePackage` job

### ISSUE THREAD

**Issue by marcusmoore** [tighten/novapackages#139]
The `UserRatePackage` job (called from `ratePackage()` in the `User` model) is marked as a queued job. We should either move it off of the default queue so it doesn't get blocked by system-generated queued jobs or, I think preferrably, un-queue it.

**Comment by mattstauffer** [comment]
My guess about why it's queued is because I thought it would make it a tiny bit faster when the user hits the "rate package" buttons, but I think just un-queuing it is fine for now!
