### ISSUE TITLE
Catch `SelfAuthoredRatingException` and return an error

### ISSUE THREAD

**Issue by mattstauffer** [tighten/novapackages#140]
![image](https://user-images.githubusercontent.com/151829/131854850-074c5e3a-33c6-4f4c-bf78-e1269489bdde.png)

In `UserRatePackage` we catch this exceptional situation and just throw an exception, which bubbles up to Bugsnag, when we should really *do* something with it.

Right now that job is queued, so nothing really happens.

Once we un-queue the job (#139) we could actually catch the exception in the controller and return an error, which feels appropriate.

**Comment by marcusmoore** [comment]
[This was already set up](https://github.com/tighten/novapackages/blob/d02340c4bd25555ff39c59c2ed7fc7166d1154e9/app/Http/Controllers/InternalApi/RatingsController.php#L25-L32) and works now that `UserRatePackage` is unqueued 😄  (#144)
