### ISSUE TITLE
Package Author is broken/empty - Broken json<->select mapping

### ISSUE THREAD

**Issue by nea** [tighten/novapackages#173]
Ahoy

It seems the issue reported in #50 is happening again:
![image](https://user-images.githubusercontent.com/392035/147569284-5ce42999-009c-4681-943c-3585ae12c05f.png)

Trying to add a package the author field is empty-filled with the given json not being correctly parsed, therefore not able to select an entry correctly.

Thanks for the whole site and package overview 🙇 ^^'

**Comment by marcusmoore** [comment]
Thanks for reporting this @nea. It should be fixed for you now 😄
