### ISSUE TITLE
Screenshots not saving

### ISSUE THREAD

**Issue by simonhamp** [tighten/novapackages#203]
I've removed some old screenshots for [my package](https://novapackages.com/packages/simonhamp/laravel-nova-csv-import) and attempted to upload new ones. They appear to upload, but when I hit 'save' they don't appear.

Is there some approval process they need to go through?

**Comment by marcusmoore** [comment]
Hi @simonhamp. There isn't an approval process so you're hitting a bug. Thanks for reporting. I'll investigate tomorrow 😄

**Comment by marcusmoore** [comment]
Thanks for reporting this @simonhamp. I was able to get it fixed and also manually associated the screenshots you uploaded previously to your package 😄

**Comment by simonhamp** [comment]
Legend! Thank you

**Comment by mziraki** [comment]
@marcusmoore this bug still exists!

**Comment by marcusmoore** [comment]
Thanks for reporting @mziraki. This is fixed (again). 

I see you have multiple packages and I don't want to manually associate screenshots to the wrong package so please feel free to re-upload them.

Thanks again 😄

**Comment by mziraki** [comment]
@marcusmoore thanks, I noticed one minor mistake in screenshots url 
![image](https://user-images.githubusercontent.com/6510195/183778014-3cc980af-41b6-4b19-b273-03fbd2a63485.png)
and I think there are lots of unlinked screenshots in storage, I don't know if there is any regular purge schedule, but it will be useful if it existed.

**Comment by marcusmoore** [comment]
Thanks, I noticed that as well and it should be a quick fix I'm planning on tackling tomorrow 👍🏾 

We have a scheduled task that cleans up abandoned screenshots too 😄
