### ISSUE TITLE
More API data [enhancement]

### ISSUE THREAD

**Issue by Muetze42** [tighten/novapackages#210]
Would it be possible to set up an API route to get the current ratings of NovaPackages to use them in an infobox etc.?

**Comment by marcusmoore** [comment]
Hello @Muetze42, that should be possible. Can you provide a little more information on your use-case? Thanks!

**Comment by Muetze42** [comment]
I have an infobox with data from Github and Composer and would like to include NovaPackages there including ratings (number, score) if available.

https://huth.it/nova-packages

**Comment by marcusmoore** [comment]
@Muetze42 Ah gotcha! Nice! 

We're open to PRs if you would like to take a swing at implementing the functionality yourself. Otherwise I'll look into implementing it in the future at some point 😄

**Comment by Muetze42** [comment]
OK. Good to know. I'll have a look in the next few days.

Currently I just get the data from the website, but that's not so elegant.

https://github.com/Muetze42/huth.it/blob/main/app/Console/Commands/Package/UpdateNovaPackagesCommand.php#L59
