### ISSUE TITLE
Support emoji in installation instructions

### ISSUE THREAD

**Issue by mattstauffer** [tighten/novapackages#22]
I havent' tested it but this makes me think we may not:

GitHub:
![image](https://user-images.githubusercontent.com/151829/73594084-c495d580-44d8-11ea-9c9a-3f50456b9ca0.png)

NovaPackages:
![image](https://user-images.githubusercontent.com/151829/73594088-c95a8980-44d8-11ea-893e-9653d59a8b58.png)

**Comment by mattstauffer** [comment]
Tried to manually add the emoji to the installation instructions column just to see if the database supported it and got this error:

![image](https://user-images.githubusercontent.com/151829/73594098-e98a4880-44d8-11ea-818f-7e90bf9ead0e.png)

It's a `text` field, char set `utfmb4`, collation `utf8mb4_unicode_ci`

**Comment by mattstauffer** [comment]
Both my local and the production tables have the same setup:

MySQL 5.7
column character_set utf8mb4
column collation mtf8mb4_unicode_ci
table DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

I can insert an emoji into the instructions column of my local but not the production. WTF?

**Comment by marcusmoore** [comment]
> Tried to manually add the emoji to the installation instructions column just to see if the database supported it and got this error:

@mattstauffer I just realized that TablePlus doesn't seem to default to using the table's character set but you can change it via `Connection -> View Using Encoding`:

![image](https://user-images.githubusercontent.com/1141514/73789654-08e0da00-4754-11ea-9999-0ff4863d2c6b.png)

Locally, TablePlus' `View Using Encoding` was set to `utf8` and showed `?` for emojis:
![image](https://user-images.githubusercontent.com/1141514/73790049-b05e0c80-4754-11ea-89a9-df1c82a04e43.png)

but when I switched it to `utf8mb4` it displayed the emojis correctly:
![image](https://user-images.githubusercontent.com/1141514/73790107-c79cfa00-4754-11ea-9dd0-eae86686e465.png)

---

My browser shows emojis locally so I'm wondering if we check the production database in "utf8mb4" mode in TablePlus, do we see `?` or emojis?

**Comment by mattstauffer** [comment]
.... regardless of that, i just went to test it and now ... it just worked?

What the actual hell.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/151829/73873077-ebc50d80-481e-11ea-9059-4c2cf618ed89.png">
