### ISSUE TITLE
Something wrong with login session handling - doesn't stick

### ISSUE THREAD

**Issue by eugenevdm** [tighten/novapackages#40]
There appears to be something wrong with the session handling of nova packages. Whenever I have closed by browser or stay away for a very short while, I have to log in again. It seems to stay logged in for only one browser session.

Not really sure how I to isolate, but I guess trying to investigate cookie lifetime?

**Comment by marcusmoore** [comment]
Hi @eugenevdm, sorry for the long delay in responding 😅 

We're currently expiring sessions after two hours. I tested it today and it seems to be working as expected. I'm going to close this issue but please respond if you're experiencing a shorter session expiration and I'll reopen it.

Have a great day 😄
