### ISSUE TITLE
Fix full-width flash success messages

### ISSUE THREAD

**Issue by mattstauffer** [tighten/novapackages#45]
![image](https://user-images.githubusercontent.com/151829/76346462-7051f280-62db-11ea-8683-01ecc89f68b7.png)

Reproduce: log in as admin, disable package.

**Comment by devingray** [comment]
@mattstauffer 

Can you define "fix" I'd like to take this on. 

My idea would be an alpine js component with an onload event listener that an be triggered from Livewire or Vue if needed. 

Something like

`$this->dispacthBrowserEvent('alert', ['success', 'You are rock solid'])`

**Comment by mattstauffer** [comment]
@devingray Main thing is just to fix that the CSS should be centered and max-width'ed to match the container :)
