### ISSUE TITLE
Back button breaks homepage in Safari.

### ISSUE THREAD

**Issue by jakeryansmith** [tighten/novapackages#57]
When using Safari 13.02 if you navigate from the homepage by clicking on a package name, then click the back button (either the Browser or the link on the page) the filtering on the homepage no longer works.
The console does not show any errors. Clicking a filter link does nothing. Search does not trigger anything either.

**Comment by mattstauffer** [comment]
I can't reproduce. Looks like it may be fixed? Please re-open if it's still an issue. Thanks!
