### ISSUE TITLE
Lost package ownership after changing github account type to organisation

### ISSUE THREAD

**Issue by muzafferdede** [tighten/novapackages#68]
Long time ago I created a nova package [nemrutco/nova-filterable-metrics](https://github.com/nemrutco/nova-filterable-metrics) using a github personal account on novapackages. Then i converted that account type to an organizations on github ([nemrutco](https://github.com/nemrutco)) and assigned my another personal account (@muzafferdede) as administrator. I lost ownership on [novapackages](https://novapackages.com/packages/nemrutco/nova-filterable-metrics) now.  

I think novapackages does not track account type changes on github side after initializing account. Not sure if there is a way to check these changes on github side or a way to link organisations to personal accounts. 

Any solution for this issue? 

ping @mattstauffer

**Comment by mattstauffer** [comment]
Yah, we don't track this after the fact. opening an issue here is the best call.. but it's also helpful if my email inbox isn't an eternal hole of death. 🤦🏻‍♂️

I'll dig into it and see if I can fix it.

**Comment by mattstauffer** [comment]
@muzafferdede Think I fixed it; let me know!

**Comment by muzafferdede** [comment]
Yup, i can confirm it is fixed. Thanks Matt.
