### ISSUE TITLE
filters are missing

### ISSUE THREAD

**Issue by vwasteels** [tighten/novapackages#69]
in the package list, the sidebar with filters is not showing anymore (chrome , mac , desktop , no zoom)

**Comment by mattstauffer** [comment]
Can't reproduce. May have been temporary? Please re-open if still presenting.

**Comment by vwasteels** [comment]
Yes it's still missing,
There used to be a sidebar with filters on the left, I can't see it anymore :

![Screenshot -  2020-10-30 à 10 04 04](https://user-images.githubusercontent.com/1151398/97680612-42eacc80-1a97-11eb-888f-fb6cb2e9f3b4.jpg)

**Comment by vwasteels** [comment]
note : this is chrome 86 on MacOS Mojave 10.14

**Comment by marcusmoore** [comment]
Hm...this is very interesting. I'm running on macOS 10.15 and don't have the issue in Chrome, Brave, Firefox, or Safari...

![image](https://user-images.githubusercontent.com/1141514/97744208-12f5f600-1aa4-11eb-92be-2cd68f13f83f.png)

**Comment by vwasteels** [comment]
Ok found it... it was related to one of the extensions I was using with Chrome ... sorry to bother with that, thank you !!
