### ISSUE TITLE
add option for "exact matches only" search and/or respect quoted words as being "exact only"

### ISSUE THREAD

**Issue by vesper8** [tighten/novapackages#73]
I don't find it useful to be shown search results on "tabs" and "tab" when I search for "tags"

I really only care about seeing packages related to "tags"

I realize what's happening here.. but it's not actually helpful. On google there would be text saying "also showing results for 'tabs', click here to only see results for 'tags'"

Or, on many search engines if I wrapped tags in quotes, it would understand that I only want to see exact matches

Would be nice to see this added.

Thanks for this most useful resources in any case

**Comment by marcusmoore** [comment]
Hey there @vesper8 👋🏾 

Searching for `"tags"` will now make sure the results include that keyword. Searching for multiple items (fe `"tags" "input"`) is also supported 😄
