### ISSUE TITLE
Not able to delete

### ISSUE THREAD

**Issue by devingray** [tighten/novapackages#81]
Hi @mattstauffer 

I got an email asking to remove a package if it is no longer maintained. There is not an option I can see to delete the package. 

Happy to PR for this if it doesn't exist, but also, I could be dumb/not looking correctly/both and am missing it

**Comment by marcusmoore** [comment]
Thank you and you're correct. We definitely pushed that PR too soon 😬 

Thank you for the work you started on #84

**Comment by devingray** [comment]
💯 It happens to the best of us.

**Comment by dillingham** [comment]
@marcusmoore would love the ability to delete my packages

**Comment by marcusmoore** [comment]
Hey @dillingham. I'm planning on working on this soon. In the meantime, are there any packages you would like me to manually remove? 😄

**Comment by dillingham** [comment]
@marcusmoore all of them, thanks :)

Including these which I assigned to 64 by mistake while tinkering

- https://novapackages.com/packages/dillingham/nova-ajax-select
- https://novapackages.com/packages/dillingham/nova-minimal-theme

**Comment by marcusmoore** [comment]
@dillingham done. Thanks for your patience 😄

**Comment by dillingham** [comment]
@marcusmoore thank you! Much appreciated
