### ISSUE TITLE
Production Mail Variables Are Misleading

### ISSUE THREAD

**Issue by devingray** [tighten/novapackages#82]
<img width="180" alt="subject@2x" src="https://user-images.githubusercontent.com/11573528/97832117-9f9eef00-1d04-11eb-9192-d4f6e0fb8306.png">

Please see the screenie, the production MAIL variables are coming from hello@example.com, this will eventually be marked as spam and rejected from mail servers

**Comment by marcusmoore** [comment]
We missed updating those in production 😅 . Thank you for the heads up!

**Comment by devingray** [comment]
See a new email came in and it was glorious
