### ISSUE TITLE
Avoid sending error emails if GitHub is down

### ISSUE THREAD

**Issue by bakerkretzmar** [tighten/novapackages#85]
See https://twitter.com/nyratas/status/1323212308760399872 and #75.

I got this email too, I _think_ GitHub went down for a hot second and a lot of people may have gotten similar emails.

We should check if GitHub itself is down before sending these emails, or:

- **only send them when the link has been broken for a while**
- cancel sending them if we would be sending to > a certain number of people

**Comment by marcusmoore** [comment]
We may have also hit GitHub's rate-limiter. Going to dive into this later today. Sorry for the inconvenience.

**Comment by marcusmoore** [comment]
We've disabled the checking of package statuses and the sending of emails for now. Going to re-think this and implement it in a way that doesn't bombard our users with emails 😅
