### ISSUE TITLE
Unable to upload audio files

### ISSUE THREAD

**Issue by HenryJBN** [tighten/novapackages#92]
Hi,
Thanks for this awesome package.
I encountered an issue while uploading files. I could successfully upload image files but when i attempted to upload an audio file, it threw an error. Kindly see attached screenshot. I had tried to use Media::make() instead of Files::make() but no headway.
What do I need to change?

Thanks 

### Resource 

`public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            BelongsTo::make('Album')->showCreateRelationButton(function ($request) {
                return true;
            })->required(),
            Text::make(__('Title'), 'title')->required(),
            Markdown::make('Description'),
            Text::make(__('Type'), 'type')->required(),
            Files::make('Upload Song', 'songs')->required(),

        ];
    }`

### Model

`class Song extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = ['album_id','title', 'description', 'type'];

    public function album()
    {
        return $this->belongsTo(Album::class);
    }

    public function registerMediaCollections(): void
    {
            $this
                ->addMediaCollection('songs')
                ->acceptsMimeTypes(['audio/mpeg','video/mpeg'])
                ->singleFile();

    }
}
![Screenshot at Jan 21 05-27-22](https://user-images.githubusercontent.com/54439452/105280726-c0137280-5baa-11eb-8e89-6288abb5f976.png)
`

**Comment by marcusmoore** [comment]
Hi there @HenryJBN,

This repo is the codebase for [novapackages.com](https://novapackages.com/) and can't provide support for the packages listed on the site. I think the package you're working with has an issue tracker on their repo: [https://github.com/whitecube/nova-flexible-content](https://github.com/whitecube/nova-flexible-content)

Have a good day 😄
