### ISSUE TITLE
Packagist returning a result with no `package` key which we don't handle well

### ISSUE THREAD

**Issue by mattstauffer** [tighten/novapackages#93]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/151829/105505315-d0a11700-5c96-11eb-90a9-97b85b2515be.png">

My gut is someone deleted the package from Packagist and we're getting an error result from packagist but we're not handling it correctly.

**Comment by marcusmoore** [comment]
I'll work on this in the near future 👍

**Comment by marcusmoore** [comment]
Having a similar issue when displaying packages
![image](https://user-images.githubusercontent.com/1141514/106335557-e89e0b00-6241-11eb-82e0-49b9f3a3bce3.png)

In both cases we're not handling the `PackagistException` and also not checking to make sure those values were returned before using them (obviously). I'll work on both issues soon.

**Comment by marcusmoore** [comment]
This was handled in eeb5ec91a747acca59992df9b23428bce16a9ee3. Further work can be done to mark the package as unavailable/abandoned which is being tracked in #63
